//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: V1.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _WXAPP_RES_V1_BASE_CLASSES_H
#define _WXAPP_RES_V1_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/notebook.h>
#include <wx/panel.h>
#include <wx/imaglist.h>
#include <wx/textctrl.h>
#include <wx/button.h>
#include <wx/choice.h>
#include <wx/arrstr.h>
#include <wx/listbox.h>
#include <wx/hyperlink.h>
#include <wx/wizard.h>
#include <vector>
#include <wx/filepicker.h>
#include <wx/statbox.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class MainFrame : public wxFrame
{
protected:
    wxStaticText* lblTestVersion;
    wxNotebook* nbMain;
    wxPanel* panelSign;
    wxStaticText* lblFileToSign;
    wxTextCtrl* inpFileToSign;
    wxButton* btnFileToSign;
    wxStaticText* lblSignAs;
    wxChoice* choSignAs;
    wxStaticText* lblCertPass;
    wxTextCtrl* inpCertSignerPass;
    wxButton* btnSign;
    wxPanel* panelVerify;
    wxStaticText* lblSignatureFile;
    wxTextCtrl* inpFileToVerify;
    wxButton* btnFileToVerify;
    wxPanel* panelCerts;
    wxPanel* panelCertsList;
    wxListBox* listCerts;
    wxButton* btnAddCert;
    wxStaticText* lblCertInfoName;
    wxStaticText* outCertInfoName;
    wxStaticText* lblCertInfoEmail;
    wxStaticText* outCertInfoEmail;
    wxStaticText* lblCertInfoCPF;
    wxStaticText* outCertInfoCPF;
    wxStaticText* lblCertInfoAC;
    wxStaticText* outCertInfoAC;
    wxStaticText* lblCertInfoNotBefore;
    wxStaticText* outCertInfoNotBefore;
    wxStaticText* lblCertInfoNotAfter;
    wxStaticText* outCertInfoNotAfter;
    wxPanel* panelCertsFirst;
    wxButton* btnFirstCert;
    wxHyperlinkCtrl* linkGetCertificate;
    wxPanel* panelHelp;
    wxStaticText* m_staticText211;
    wxHyperlinkCtrl* m_hyperLink213;
    wxStaticText* m_staticText194;
    wxStaticText* outOpenICPVer;
    wxStaticText* m_staticText198;
    wxStaticText* outLibICPVer;
    wxStaticText* m_staticText202;
    wxStaticText* outWxVer;

protected:

public:
    wxStaticText* GetLblTestVersion() { return lblTestVersion; }
    wxStaticText* GetLblFileToSign() { return lblFileToSign; }
    wxTextCtrl* GetInpFileToSign() { return inpFileToSign; }
    wxButton* GetBtnFileToSign() { return btnFileToSign; }
    wxStaticText* GetLblSignAs() { return lblSignAs; }
    wxChoice* GetChoSignAs() { return choSignAs; }
    wxStaticText* GetLblCertPass() { return lblCertPass; }
    wxTextCtrl* GetInpCertSignerPass() { return inpCertSignerPass; }
    wxButton* GetBtnSign() { return btnSign; }
    wxPanel* GetPanelSign() { return panelSign; }
    wxStaticText* GetLblSignatureFile() { return lblSignatureFile; }
    wxTextCtrl* GetInpFileToVerify() { return inpFileToVerify; }
    wxButton* GetBtnFileToVerify() { return btnFileToVerify; }
    wxPanel* GetPanelVerify() { return panelVerify; }
    wxListBox* GetListCerts() { return listCerts; }
    wxButton* GetBtnAddCert() { return btnAddCert; }
    wxStaticText* GetLblCertInfoName() { return lblCertInfoName; }
    wxStaticText* GetOutCertInfoName() { return outCertInfoName; }
    wxStaticText* GetLblCertInfoEmail() { return lblCertInfoEmail; }
    wxStaticText* GetOutCertInfoEmail() { return outCertInfoEmail; }
    wxStaticText* GetLblCertInfoCPF() { return lblCertInfoCPF; }
    wxStaticText* GetOutCertInfoCPF() { return outCertInfoCPF; }
    wxStaticText* GetLblCertInfoAC() { return lblCertInfoAC; }
    wxStaticText* GetOutCertInfoAC() { return outCertInfoAC; }
    wxStaticText* GetLblCertInfoNotBefore() { return lblCertInfoNotBefore; }
    wxStaticText* GetOutCertInfoNotBefore() { return outCertInfoNotBefore; }
    wxStaticText* GetLblCertInfoNotAfter() { return lblCertInfoNotAfter; }
    wxStaticText* GetOutCertInfoNotAfter() { return outCertInfoNotAfter; }
    wxPanel* GetPanelCertsList() { return panelCertsList; }
    wxButton* GetBtnFirstCert() { return btnFirstCert; }
    wxHyperlinkCtrl* GetLinkGetCertificate() { return linkGetCertificate; }
    wxPanel* GetPanelCertsFirst() { return panelCertsFirst; }
    wxPanel* GetPanelCerts() { return panelCerts; }
    wxStaticText* GetStaticText211() { return m_staticText211; }
    wxHyperlinkCtrl* GetHyperLink213() { return m_hyperLink213; }
    wxStaticText* GetStaticText194() { return m_staticText194; }
    wxStaticText* GetOutOpenICPVer() { return outOpenICPVer; }
    wxStaticText* GetStaticText198() { return m_staticText198; }
    wxStaticText* GetOutLibICPVer() { return outLibICPVer; }
    wxStaticText* GetStaticText202() { return m_staticText202; }
    wxStaticText* GetOutWxVer() { return outWxVer; }
    wxPanel* GetPanelHelp() { return panelHelp; }
    wxNotebook* GetNbMain() { return nbMain; }
    MainFrame(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("OpenICPBr"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(-1,-1), long style = wxDEFAULT_FRAME_STYLE|wxTAB_TRAVERSAL);
    virtual ~MainFrame();
};


class wizAddCert : public wxWizard
{
protected:
    std::vector<wxWizardPageSimple*> m_pages;

    wxWizardPageSimple* wpAddCertLoc;
    wxStaticText* lblCertFile;
    wxFilePickerCtrl* fpCertFile;
    wxWizardPageSimple* wpAddCertPass;
    wxStaticText* lblCertPass;
    wxTextCtrl* inpCertPass;
    wxStaticText* m_staticText145;
    wxWizardPageSimple* wpAddCertInfo;
    wxStaticText* lblCertName;
    wxStaticText* outCertName;
    wxStaticText* lblCertEmail;
    wxStaticText* outCertEmail;
    wxStaticText* lblCertCPF;
    wxStaticText* outCertCPF;
    wxStaticText* lblCertAC;
    wxStaticText* outCertAC;
    wxStaticText* lblCertNotBefore;
    wxStaticText* outCertNotBefore;
    wxStaticText* lblCertNotAfter;
    wxStaticText* outCertNotAfter;

protected:

public:
    wxStaticText* GetLblCertFile() { return lblCertFile; }
    wxFilePickerCtrl* GetFpCertFile() { return fpCertFile; }
    wxWizardPageSimple* GetWpAddCertLoc() { return wpAddCertLoc; }
    wxStaticText* GetLblCertPass() { return lblCertPass; }
    wxTextCtrl* GetInpCertPass() { return inpCertPass; }
    wxStaticText* GetStaticText145() { return m_staticText145; }
    wxWizardPageSimple* GetWpAddCertPass() { return wpAddCertPass; }
    wxStaticText* GetLblCertName() { return lblCertName; }
    wxStaticText* GetOutCertName() { return outCertName; }
    wxStaticText* GetLblCertEmail() { return lblCertEmail; }
    wxStaticText* GetOutCertEmail() { return outCertEmail; }
    wxStaticText* GetLblCertCPF() { return lblCertCPF; }
    wxStaticText* GetOutCertCPF() { return outCertCPF; }
    wxStaticText* GetLblCertAC() { return lblCertAC; }
    wxStaticText* GetOutCertAC() { return outCertAC; }
    wxStaticText* GetLblCertNotBefore() { return lblCertNotBefore; }
    wxStaticText* GetOutCertNotBefore() { return outCertNotBefore; }
    wxStaticText* GetLblCertNotAfter() { return lblCertNotAfter; }
    wxStaticText* GetOutCertNotAfter() { return outCertNotAfter; }
    wxWizardPageSimple* GetWpAddCertInfo() { return wpAddCertInfo; }
    wizAddCert(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Instalação de certificado digital"), const wxBitmap& bmp = wxNullBitmap, const wxPoint& pos = wxDefaultPosition, long style = wxDEFAULT_DIALOG_STYLE|wxCAPTION|wxRESIZE_BORDER|wxMINIMIZE_BOX);
    wxWizardPageSimple* GetFirstPage() const { if(!m_pages.empty()) return m_pages.at(0); return NULL; }
    virtual ~wizAddCert();
};

#endif
